import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  mainContainer: {
    paddingHorizontal: 16,
    backgroundColor: '#161515',
    height: '100%',
  },
  container: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
    alignItems: 'center',
  },
  skipText: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'LufgaMedium',
    fontWeight: 500,
  },
  titleText: {
    color: 'white',
    fontSize: 38,
    fontFamily: 'LufgaBold',
    fontWeight: 700,
  },
  signContainer: {
    flexDirection: 'row',
    marginTop: 50,
    alignItems: 'center',
    gap: 22,
    justifyContent: 'center',
  },
  signText: {
    color: '#CCFA4C',
    fontSize: 22,
    fontFamily: 'LufgaRegular',
    fontWeight: 400,
  },
  signup: {
    color: 'white',
    fontSize: 22,
    fontFamily: 'LufgaRegular',
    fontWeight: 400,
  },
  line: {
    width: 1,
    height: 37,
    backgroundColor: 'white',
  },
  input: {
    width: '100%',
    paddingHorizontal: 34,
    paddingVertical: 27,
    backgroundColor: '#222121',
    marginTop: 24,
    fontFamily: 'LufgaRegular',
    fontWeight: 400,
    fontSize: 16,
    borderColor: '#CCFA4C',
    borderWidth: 1,
    borderRadius: 50,
  },
  buttonContainer:{
    display:'flex',
    flexDirection:'row',
    justifyContent:'space-between',
    marginTop:24,
  },
  rememberWrapper:{
    display:'flex',
    flexDirection:'row',
    alignItems:'center',
    gap:7,
  },
  rememberText:{
    color:'white',
    fontSize:16,
    fontFamily:'LufgaRegular',
    fontWeight:400,
    marginRight:7,
  },
  forgetText:{
    color:'white',
    fontSize:16,
    fontFamily:'LufgaRegular',
    fontWeight:400,
  },
  circle:{
    width:16,
    height:16,
    borderRadius:100,
    backgroundColor:'#CCFA4C',
    borderWidth:1,
    borderColor:'#CCFA4C',
  },
  button: {
    paddingVertical: 18,
    alignItems: 'center',
    marginTop: 44,
    borderRadius: 100,
    backgroundColor: '#CCFA4C',
  },
  buttonText: {
    color: '#161515',
    fontSize: 18,
    fontFamily: 'LufgaMedium',
    fontWeight: 500,
  },
  orText:{
    color:'white',
    fontSize:17,
    fontFamily:'LufgaRegular',
    fontWeight:400,
    marginTop:20,
    textAlign:'center',
  },
  socialContainer:{
    display:'flex',
    flexDirection:'row',
    marginTop:28,
    gap:30,
    alignItems:'center',
    justifyContent:'center',
    marginBottom:100,
  },
  SocialIconbox:{
    width:44,
    height:44,
    borderRadius:100,
    backgroundColor:'#222121',
    alignItems:'center',
    justifyContent:'center',
  },
  footer:{
    display:'flex',
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'center',
    marginTop:24,
    gap:7,
  },
  footerText:{
    color:'white',
    fontSize:18,
    fontFamily:'LufgaRegular',
    fontWeight:400,
  },
  footerSign:{
    color:'#CCFA4C',
    fontSize:18,
    fontFamily:'LufgaRegular',
    fontWeight:400,
  }
});

export default styles;
